# setup
setup: scan

# Loss
criterion: scan
criterion_kwargs:
   entropy_weight: 5.0

# Weight update
update_cluster_head_only: False # Update full network in SCAN
num_heads: 1 # Only use one head

# Model
backbone: resnet18

# Dataset
train_db_name: svhn
val_db_name: svhn
num_classes: 10
num_neighbors: 20

# Transformations
augmentation_strategy: ours
augmentation_kwargs:
   crop_size: 32
   normalize:
      mean: [0.4376, 0.4437, 0.4728]
      std: [0.1980, 0.2010, 0.1970]
   num_strong_augs: 4
   cutout_kwargs:
     n_holes: 1
     length: 16
     random: True

transformation_kwargs:
   crop_size: 32
   normalize:
      mean: [0.4376, 0.4437, 0.4728]
      std: [0.1980, 0.2010, 0.1970]

# Hyperparameters
optimizer: adam
optimizer_kwargs:
   lr: 0.0001
   weight_decay: 0.0001
epochs: 50
batch_size: 128
num_workers: 8

# Scheduler
scheduler: constant
