# setup
setup: selflabel

# ema
use_ema: False

# Threshold
confidence_threshold: 0.99

# Criterion
criterion: confidence-cross-entropy
criterion_kwargs:
   apply_class_balancing: True

# Model
backbone: resnet18
num_heads: 1

# Dataset
train_db_name: svhn
val_db_name: svhn
num_classes: 10

# Transformations
augmentation_strategy: ours
augmentation_kwargs:
   crop_size: 32
   normalize:
      mean: [0.4376, 0.4437, 0.4728]
      std: [0.1980, 0.2010, 0.1970]
   num_strong_augs: 4
   cutout_kwargs:
     n_holes: 1
     length: 16
     random: True

transformation_kwargs:
   crop_size: 32
   normalize:
      mean: [0.4376, 0.4437, 0.4728]
      std: [0.1980, 0.2010, 0.1970]

# Hyperparameters
epochs: 25
optimizer: adam
optimizer_kwargs:
   lr: 0.0001
   weight_decay: 0.0001
batch_size: 1000
num_workers: 8

# Scheduler
scheduler: constant
